### PR TITLE
Remove nonexisting constant

### PR DESCRIPTION
**Pull request by thorewi**

### CODE REVIEW

**Comment by bakerman** [comment]
Will this be merged or is the project already abandoned?

**Comment by paveljanda** [comment]
The constant was there in the past. Should we update also the dependencies? Or am I missing any info (because of nonexisting description?)

**Comment by thorewi** [comment]
yes, I haven't done any research what happened with the constant... after quick check it seems it wasn't used at all... so we can probably safely remove it and it shouldn't be a BC...

**Comment by f3l1x** [comment]
Resolved https://github.com/contributte/api-router/commit/206bde884bfb72e2489ce12d0aa8592a0fe6b069

**Pull request closed without merging**
