### PR TITLE
Update for new nette router with use getRouters()

### PR DESCRIPTION
**Pull request by mstefan21**

### CODE REVIEW

**Comment by paveljanda** [comment]
Ok, thanks.

Could you please specify in [composer.json](https://github.com/contributte/api-router/blob/master/composer.json) file the lowest supported nette routers version? Thanks 👍

**Comment by mstefan21** [comment]
@paveljanda yes, sure, this week I will add composer package version change

**Comment by f3l1x** [comment]
It looks like loong week. @mstefan21 :-D

**Comment by f3l1x** [comment]
I will specify it by myself. Thanks anyway.

**Pull request merged**
